# Basic
title: Weihan Li
subtitle: Personal blog
description: 
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Weihan Li
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Data Science / Quant
url: "www.weihanli.com"

# Comment
comment:
    disqus: weihanli
    duoshuo: weihanli 

# Social
social:
    weibo: Goularttt 
    github: saintat1
    # twitter: 
    mail: wl2525@columbia.edu
    linkedin: weihan-li-296255105

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
#baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Blog, description: archive, url: '/archive'}   
    - {title: Tag, description: tags, url: '/tags'}      
    - {title: CV, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


